SELECT 
    B.TITLE, R.BOARD_ID, R.REPLY_ID, R.WRITER_ID, R.CONTENTS, DATE_FORMAT(R.CREATED_DATE, '%Y-%m-%d') AS CREATED_DATE
FROM 
    USED_GOODS_REPLY R
    JOIN 
        USED_GOODS_BOARD B
        ON R.BOARD_ID = B.BOARD_ID
WHERE
    B.CREATED_DATE LIKE '2022-10%'
ORDER BY
    R.CREATED_DATE ASC,
    B.TITLE ASC